/* Generated by Together */

public abstract class Event {
    private long eventTime;
    public Event(long evtTime) {
        eventTime = evtTime;
    }
    public boolean ready() {
        return System.currentTimeMillis() >= eventTime;
    }
    abstract public void action();
    abstract public String description();
}
