/* Generated by Together */

public class LifeAtCMUControls extends Controller {
	private boolean studying = false;
    private boolean sleeping = false;
    private boolean eating = false;
    private boolean playing = false;	// Jeez, what a life!

    private class StartStudying extends Event {
        public StartStudying(long eventTime) {
            super(eventTime);
        }
        public void action() {
			studying = true;
        }
        public String description() {
            return "Can't you see I'm studying Java?";
        }
    }
    private class StopStudying extends Event {
        public StopStudying(long eventTime) {
            super(eventTime);
        }
        public void action() {
			studying = false;
        }
        public String description() {
            return "I'm sick of studying Java!";
        }
    }
    private class StartSleeping extends Event {
        public StartSleeping(long eventTime) {
            super(eventTime);
        }
        public void action() {
			sleeping = true;
        }
        public String description() {
            return "Buzz off, I'm sleeping!";
        }
    }
    private class StopSleeping extends Event {
        public StopSleeping(long eventTime) {
            super(eventTime);
        }
        public void action() {
			sleeping = false;
        }
        public String description() {
            return "I'm awake now, think I'll study Java.";
        }
    }

        private class StartEating extends Event {
        public StartEating(long eventTime) {
            super(eventTime);
        }
        public void action() {
			eating = true;
        }
        public String description() {
            return "I'm hungry, let's eat!";
        }
    }
    private class StopEating extends Event {
        public StopEating(long eventTime) {
            super(eventTime);
        }
        public void action() {
			eating = false;
        }
        public String description() {
            return "I'm full.";
        }
    }

    private class AnotherWeekAtCMU extends Event {
        public AnotherWeekAtCMU(long eventTime) {
            super(eventTime);
        }
        public void action() {
            long tm = System.currentTimeMillis();
            addEvent(new StartSleeping(tm));		// Sunday at midnight
            addEvent(new StopSleeping(tm + 2800)); // Monday at 8 am
            addEvent(new StartStudying(tm + 2801));
            addEvent(new StartEating(tm + 2860));
            // etc....
        }
        public String description() {
            return "Starting another week at CMU";
        }
    }

    public static void main(String[] args) {
        LifeAtCMUControls life = new LifeAtCMUControls();
        long tm = System.currentTimeMillis();
        life.addEvent(life.new AnotherWeekAtCMU(tm));
        life.run();
    }
}
