/* Generated by Together 
 *  Homework 7
 * Generate one Generation of trees and then evolve for 5 times.
 * Date: Dec 5, 2011    
 * Andrew ID: fanc
 * File Name: TestEvolver.java;
 * Compiler: Eclipse SDK  Version: 3.7.0  Build id: I20110613-1736
 */
import java.util.*;
import java.text.*;
/**
 * @author Fan CHEN
*/
public class TestEvolver {
	static int maxDepth = 5;
	static Random rand = new Random();
	static int numTrees = 500;
	public static Evolver[] theMaker;

	public static void main(String[] args) {
		Scanner keyboard = new Scanner(System.in);
		System.out.println("Enter the name of a file:(hint:Data2.dat)");
		String fName = keyboard.nextLine();
		DataSet ds = new DataSet(fName);//new dataSet
		Node[] ops = { new Plus(), new Minus(), new Mult(), new Divide() };
		OperatorFactory o = new OperatorFactory(ops);
		TerminalFactory t = new TerminalFactory(ds.numIndepVars());
		Generation g = new Generation(numTrees, o, t, maxDepth, rand);//new generation
		g.evalAll(ds);
		System.out.println("Original Generation:");
		g.printBestTree();
		//g.printAll();
		theMaker = new Evolver[5];
		
		for (int i = 0; i < 5; i++) {		
			theMaker[i] = new Evolver(g, ds, rand);
			System.out.println("Generation " + i + ":");
			g = theMaker[i].makeNewGeneration();
			g.evalAll(ds);
			g.printBestTree();
			//g.printAll();
		}
	}
}
